In [21]:
import geopandas as gpd
import folium
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

# Paso 1: Leer los datos geoespaciales
# Manzanas
import geopandas as gpd
from sqlalchemy import create_engine

# Conexión a PostGIS
engine = create_engine('postgresql://postgres:MelonSK998@localhost:5432/Poligonos')

# Función para cargar tablas desde PostGIS
def cargar_tabla(nombre_tabla):
    query = f"SELECT * FROM {nombre_tabla};"
    gdf = gpd.read_postgis(query, engine, geom_col="geom")
    return gdf

nombre_tabla = "poligonos_manzanas_agebs_colonias"
query = f"SELECT * FROM {nombre_tabla};"
gdf_manzana = gpd.read_postgis(query, engine, geom_col = "GEOM_MANZANA")

# Polígono de Coyoacán
coyoacan_polygon = gpd.read_file('../data/limites/poligonos_alcaldias_cdmx.shp')
coyoacan_polygon = coyoacan_polygon[coyoacan_polygon['NOMGEO'] == 'Coyoacán']

# Uso de suelo
shapefile_path = '../data/uso_suelo/uso-de-suelo.shp'
gdf_uso_suelo = gpd.read_file(shapefile_path, encoding='latin1')

# Eliminar registros con NaN en 'us_dscr'
gdf_uso_suelo = gdf_uso_suelo.dropna(subset=['us_dscr'])

# Alinear CRS
common_crs = gdf_manzana.crs
gdf_uso_suelo = gdf_uso_suelo.to_crs(common_crs)

# Recortar al área de Coyoacán
gdf_manzanas_coyoacan = gpd.clip(gdf_manzanas, coyoacan_polygon)
gdf_uso_suelo_coyoacan = gpd.clip(gdf_uso_suelo, coyoacan_polygon)

In [22]:
gdf_uso_suelo_coyoacan

,_id,id,alcaldi,cnt_cts,calle,no_xtrn,colonia,cdg_pst,us_dscr,superfc,dnsdd_d,niveles,altura,are_lbr,mnm_vvn,cordnds,lg_cddm,geopont,geometry
2766,2756,2755,COYOACAN,5937809,LEONARDO OLIVA,NaN,BOSQUES DE TETLAMEYA,04730,Habitacional,295.471982,Restringida 1 viv/250 m2,2.0,NaN,40.0,NaN,"-99.1544421719, 19.2995444265",http://ciudadmx.cdmx.gob.mx:8080/seduvi/fichas...,"19.2995444265,-99.1544421719",POINT (-99.15444 19.29954)
6231,6209,6208,COYOACAN,5937504,LEONARDO OLIVA,127.0,BOSQUES DE TETLAMEYA,04730,Habitacional,288.620417,Restringida 1 viv/250 m2,2.0,NaN,40.0,NaN,"-99.1545828595, 19.2998564903",http://ciudadmx.cdmx.gob.mx:8080/seduvi/fichas...,"19.2998564903,-99.1545828595",POINT (-99.15458 19.29986)
5230,5198,5197,COYOACAN,5937701,MANUEL MARTINEZ SOLORZANO,7.0,BOSQUES DE TETLAMEYA,04730,Habitacional,652.756329,Restringida 1 viv/250 m2,2.0,NaN,40.0,NaN,"-99.1530528901, 19.3002611813",http://ciudadmx.cdmx.gob.mx:8080/seduvi/fichas...,"19.3002611813,-99.1530528901",POINT (-99.15305 19.30026)
7657,7640,7639,COYOACAN,5937419,JOSE MUCI@O,56.0,BOSQUES DE TETLAMEYA,04730,Habitacional,791.632463,Restringida 1 viv/250 m2,2.0,NaN,40.0,NaN,"-99.1560858197, 19.2975072755",http://ciudadmx.cdmx.gob.mx:8080/seduvi/fichas...,"19.2975072755,-99.1560858197",POINT (-99.15609 19.29751)
9898,9892,9891,COYOACAN,5937443,SAN AGUSTIN DE LAS CUEVAS,43.0,BOSQUES DE TETLAMEYA,04730,Habitacional,402.350251,Restringida 1 viv/250 m2,2.0,NaN,40.0,NaN,"-99.1556863617, 19.2980948598",http://ciudadmx.cdmx.gob.mx:8080/seduvi/fichas...,"19.2980948598,-99.1556863617",POINT (-99.15569 19.29809)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5683,5655,5654,COYOACAN,6000847,CORONA BOREAL,32.0,PRADO CHURUBUSCO,04230,Habitacional,216.871501,Muy Baja 1 viv/200 m2,2.0,NaN,40.0,NaN,"-99.1312302375, 19.3578182753",http://ciudadmx.cdmx.gob.mx:8080/seduvi/fichas...,"19.3578182753,-99.1312302375",POINT (-99.13123 19.35782)
9126,9115,9114,COYOACAN,6001903,CRUZ DEL SUR,9.0,PRADO CHURUBUSCO,04230,Habitacional,203.752092,Muy Baja 1 viv/200 m2,2.0,NaN,40.0,NaN,"-99.1280494675, 19.3578787953",http://ciudadmx.cdmx.gob.mx:8080/seduvi/fichas...,"19.3578787953,-99.1280494675",POINT (-99.12805 19.35788)
1074,1067,1066,COYOACAN,6001954,CEFEO,10.0,PRADO CHURUBUSCO,04230,Habitacional,159.619920,Muy Baja 1 viv/200 m2,2.0,NaN,40.0,NaN,"-99.1282376093, 19.3579831834",http://ciudadmx.cdmx.gob.mx:8080/seduvi/fichas...,"19.3579831834,-99.1282376093",POINT (-99.12824 19.35798)
4115,4094,4093,COYOACAN,6001661,ERMITA IZTAPALAPA,321.0,PRADO CHURUBUSCO,04230,Habitacional,187.360718,Muy Baja 1 viv/200 m2,2.0,NaN,40.0,NaN,"-99.1285931258, 19.3581754295",http://ciudadmx.cdmx.gob.mx:8080/seduvi/fichas...,"19.3581754295,-99.1285931258",POINT (-99.12859 19.35818)
11550,11550,11549,COYOACAN,6001102,VIA LACTEA,7.0,PRADO CHURUBUSCO,04230,Habitacional,219.734225,Muy Baja 1 viv/200 m2,2.0,NaN,40.0,NaN,"-99.1304628194, 19.3582341477",http://ciudadmx.cdmx.gob.mx:8080/seduvi/fichas...,"19.3582341477,-99.1304628194",POINT (-99.13046 19.35823)

In [41]:
gdf_union = gpd.sjoin(
    gdf_manzana,
    gdf_uso_suelo_coyoacan,
    how='left',
    predicate='contains'
)

In [42]:
print(gdf_union.columns)
print(gdf_union.count())

Index(['GID_MANZANA', 'ID_MANZANA', 'GEOM_MANZANA', 'GID_AGEB', 'ID_AGEB',
       'INDEX_COLONIAS', 'ENT', 'CVEDT', 'TERRITORIO', 'DTTOLOC', 'CVEUT',
       'NOMBRE_COLONIA', 'ID_COLONIA', 'GEOM_COLONIA', 'GEOM_AGEB',
       'index_right', '_id', 'id', 'alcaldi', 'cnt_cts', 'calle', 'no_xtrn',
       'colonia', 'cdg_pst', 'us_dscr', 'superfc', 'dnsdd_d', 'niveles',
       'altura', 'are_lbr', 'mnm_vvn', 'cordnds', 'lg_cddm', 'geopont'],
      dtype='object')
GID_MANZANA       5152
ID_MANZANA        5152
GEOM_MANZANA      5152
GID_AGEB          5152
ID_AGEB           5152
INDEX_COLONIAS    5152
ENT               5152
CVEDT             5152
TERRITORIO        5152
DTTOLOC           5152
CVEUT             5152
NOMBRE_COLONIA    5152
ID_COLONIA        5152
GEOM_COLONIA      5152
GEOM_AGEB         5152
index_right       1979
_id               1979
id                1979
alcaldi           1979
cnt_cts           1979
calle             1885
no_xtrn           1102
colonia           1979
cdg_pst           1979
us_dscr           1979
superfc           1979
dnsdd_d           1930
niveles           1810
altura             148
are_lbr           1958
mnm_vvn             43
cordnds           1979
lg_cddm           1979
geopont           1979
dtype: int64

In [43]:
gdf_union = gdf_union.dropna(subset=['us_dscr'])

In [48]:
gdf_union = gdf_union.rename(columns = {
    "us_dscr": "USO_SUELO",
    "superfc": "SUPERFICIE",
    "dnsdd_d": "DNSDD_D",
    "niveles": "NIVELES",
    "altura": "ALTURA",


})

In [52]:
gdf_union.columns

Index(['GID_MANZANA', 'ID_MANZANA', 'GEOM_MANZANA', 'GID_AGEB', 'ID_AGEB',
       'INDEX_COLONIAS', 'ENT', 'CVEDT', 'TERRITORIO', 'DTTOLOC', 'CVEUT',
       'NOMBRE_COLONIA', 'ID_COLONIA', 'GEOM_COLONIA', 'GEOM_AGEB',
       'index_right', '_id', 'id', 'alcaldi', 'cnt_cts', 'calle', 'no_xtrn',
       'colonia', 'cdg_pst', 'USO_SUELO', 'SUPERFICIE', 'DNSDD_D', 'NIVELES',
       'ALTURA', 'are_lbr', 'mnm_vvn', 'cordnds', 'lg_cddm', 'geopont'],
      dtype='object')

In [54]:
gdf_union = gdf_union[['ID_MANZANA', 'GEOM_MANZANA', 'USO_SUELO', 'SUPERFICIE', 'DNSDD_D', 'NIVELES',
       'ALTURA']]

In [56]:
gdf_union["anio"] = '2017'

/home/jazzzfm/anaconda3/lib/python3.11/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [57]:
gdf_union["territorio"] = "coyoacan"

/home/jazzzfm/anaconda3/lib/python3.11/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [60]:
gdf_union

,ID_MANZANA,GEOM_MANZANA,USO_SUELO,SUPERFICIE,DNSDD_D,NIVELES,ALTURA,anio,territorio
10,9,"MULTIPOLYGON (((-99.17137 19.33699, -99.17139 ...",Habitacional con Comercio en Planta Baja,218.626810,Baja 1 viv/100 m2,3.0,NaN,2017,coyoacan
10,9,"MULTIPOLYGON (((-99.17137 19.33699, -99.17139 ...",Habitacional con Comercio en Planta Baja,186.152528,Baja 1 viv/100 m2,3.0,NaN,2017,coyoacan
16,14,"MULTIPOLYGON (((-99.16677 19.32108, -99.16673 ...",Habitacional con Comercio en Planta Baja,194.874517,Baja 1 viv/100 m2,3.0,NaN,2017,coyoacan
20,28,"MULTIPOLYGON (((-99.15877 19.34592, -99.15875 ...",Habitacional Unifamiliar,147.308647,una vivienda por cada 500.00 m2,NaN,7.5,2017,coyoacan
23,22,"MULTIPOLYGON (((-99.12024 19.35001, -99.12023 ...",Habitacional,367.124930,Muy Baja 1 viv/200 m2,2.0,NaN,2017,coyoacan
...,...,...,...,...,...,...,...,...,...
4385,4792,"MULTIPOLYGON (((-99.12159 19.35329, -99.12147 ...",Habitacional,246.771129,Muy Baja 1 viv/200 m2,2.0,NaN,2017,coyoacan
4387,4795,"MULTIPOLYGON (((-99.10555 19.31598, -99.10553 ...",Habitacional,56.397669,Baja 1 viv/100 m2,4.0,NaN,2017,coyoacan
4390,4798,"MULTIPOLYGON (((-99.12637 19.3184, -99.12636 1...",Habitacional,179.656049,Muy Baja 1 viv/200 m2,3.0,NaN,2017,coyoacan
4392,4800,"MULTIPOLYGON (((-99.14694 19.3307, -99.147 19....",Habitacional,234.783450,Muy Baja 1 viv/200 m2,2.0,NaN,2017,coyoacan
4394,4802,"MULTIPOLYGON (((-99.15008 19.30784, -99.15011 ...",Habitacional con Comercio en Planta Baja,276.559369,Baja 1 viv/100 m2,3.0,NaN,2017,coyoacan

In [61]:
gdf_union.to_postgis("datos_edafologicos_particionada", con=engine, if_exists="replace")

In [62]:
nombre_tabla = "datos_edafologicos_particionada"
query = f"SELECT * FROM {nombre_tabla};"
gdf = gpd.read_postgis(query, engine, geom_col = "GEOM_MANZANA")

In [64]:
gdf

,ID_MANZANA,GEOM_MANZANA,USO_SUELO,SUPERFICIE,DNSDD_D,NIVELES,ALTURA,anio,territorio
0,9,"MULTIPOLYGON (((-99.17137 19.33699, -99.17139 ...",Habitacional con Comercio en Planta Baja,218.626810,Baja 1 viv/100 m2,3.0,NaN,2017,coyoacan
1,9,"MULTIPOLYGON (((-99.17137 19.33699, -99.17139 ...",Habitacional con Comercio en Planta Baja,186.152528,Baja 1 viv/100 m2,3.0,NaN,2017,coyoacan
2,14,"MULTIPOLYGON (((-99.16677 19.32108, -99.16673 ...",Habitacional con Comercio en Planta Baja,194.874517,Baja 1 viv/100 m2,3.0,NaN,2017,coyoacan
3,28,"MULTIPOLYGON (((-99.15877 19.34592, -99.15875 ...",Habitacional Unifamiliar,147.308647,una vivienda por cada 500.00 m2,NaN,7.5,2017,coyoacan
4,22,"MULTIPOLYGON (((-99.12024 19.35001, -99.12023 ...",Habitacional,367.124930,Muy Baja 1 viv/200 m2,2.0,NaN,2017,coyoacan
...,...,...,...,...,...,...,...,...,...
1974,4792,"MULTIPOLYGON (((-99.12159 19.35329, -99.12147 ...",Habitacional,246.771129,Muy Baja 1 viv/200 m2,2.0,NaN,2017,coyoacan
1975,4795,"MULTIPOLYGON (((-99.10555 19.31598, -99.10553 ...",Habitacional,56.397669,Baja 1 viv/100 m2,4.0,NaN,2017,coyoacan
1976,4798,"MULTIPOLYGON (((-99.12637 19.3184, -99.12636 1...",Habitacional,179.656049,Muy Baja 1 viv/200 m2,3.0,NaN,2017,coyoacan
1977,4800,"MULTIPOLYGON (((-99.14694 19.3307, -99.147 19....",Habitacional,234.783450,Muy Baja 1 viv/200 m2,2.0,NaN,2017,coyoacan
1978,4802,"MULTIPOLYGON (((-99.15008 19.30784, -99.15011 ...",Habitacional con Comercio en Planta Baja,276.559369,Baja 1 viv/100 m2,3.0,NaN,2017,coyoacan

In [13]:
# Determinar uso de suelo predominante
uso_suelo_por_manzana = gdf_union.groupby(['IDENTIFICA', 'us_dscr', 'superfc'])\
                                 .size()\
                                 .reset_index(name='counts')

uso_suelo_predominante = uso_suelo_por_manzana.sort_values('counts', ascending=False)\
                                              .drop_duplicates('IDENTIFICA')

# Unir el uso de suelo predominante a las manzanas
gdf_manzanas_coyoacan = gdf_manzanas_coyoacan.merge(
    uso_suelo_predominante[['IDENTIFICA', 'us_dscr', 'superfc']],
    on = 'IDENTIFICA',
    how='left'
)

# Asignar 'Sin Datos' a manzanas sin información de uso de suelo
gdf_manzanas_coyoacan['us_dscr'] = gdf_manzanas_coyoacan['us_dscr'].fillna('Sin Datos')

# Simplificar geometrías (opcional)
gdf_manzanas_coyoacan['geometry'] = gdf_manzanas_coyoacan['geometry'].simplify(
    tolerance=0.0001, preserve_topology=True
)

In [ ]:
import psycopg2

# Conexión a la base de datos para ejecutar consultas SQL
conn = psycopg2.connect("dbname='Poligonos' user='developer' password='MelonSK998' host='localhost' port='5432'")
cur = conn.cursor()

# Eliminar abla existente de colonias si es necesario
cur.execute("DROP TABLE IF EXISTS poligonos_manzanas_agebs_colonias;")
conn.commit()
conn.close()

In [16]:
gdf_manzanas_coyoacan[gdf_manzanas_coyoacan["us_dscr"] != "Sin Datos"]

,IDENTIFICA,geometry,us_dscr,superfc
13,623,"POLYGON ((-99.10708 19.30122, -99.10687 19.301...",Habitacional,159.079070
14,2849,"POLYGON ((-99.1065 19.3013, -99.10638 19.30132...",Habitacional,162.412217
16,4222,"POLYGON ((-99.10499 19.30202, -99.10471 19.302...",Habitacional,161.314682
17,691,"POLYGON ((-99.10714 19.3017, -99.10597 19.3018...",Habitacional,158.658350
21,4128,"POLYGON ((-99.10742 19.3032, -99.10721 19.3032...",Habitacional,148.962777
...,...,...,...,...
4789,1956,"POLYGON ((-99.13163 19.35647, -99.13205 19.357...",Habitacional,144.837346
4790,4710,"POLYGON ((-99.1294 19.35589, -99.12934 19.3583...",Habitacional,140.539410
4791,1641,"POLYGON ((-99.12991 19.35602, -99.12982 19.358...",Habitacional,160.113995
4792,1309,"POLYGON ((-99.13043 19.3584, -99.1304 19.3584,...",Habitacional,187.164908
4793,196,"POLYGON ((-99.1313 19.358, -99.13095 19.35845,...",Habitacional,179.735373

In [ ]:
# Preparar la paleta de colores
tipos_uso_suelo = gdf_manzanas_coyoacan['us_dscr'].unique()
colores = [
    '#e41a1c', '#377eb8', '#4daf4a', '#984ea3',
    '#ff7f00', '#ffff33', '#a65628', '#f781bf', '#999999',
    '#a6cee3', '#1f78b4', '#b2df8a', '#33a02c',
    '#fb9a99', '#e31a1c', '#fdbf6f', '#ff7f00',
    '#cab2d6', '#6a3d9a', '#ffff99'
] * 10  # Multiplicar para asegurar suficientes colores

color_dict = dict(zip(tipos_uso_suelo, colores[:len(tipos_uso_suelo)]))

# Crear el mapa
centro = gdf_manzanas_coyoacan.unary_union.centroid
m = folium.Map(location=[centro.y, centro.x], zoom_start=13)

def style_function(feature):
    uso = feature['properties']['us_dscr']
    return {
        'fillColor': color_dict.get(uso, 'gray'),
        'color': 'black',
        'weight': 0.5,
        'fillOpacity': 0.7,
    }

folium.GeoJson(
    gdf_manzanas_coyoacan,
    style_function=style_function,
    tooltip=folium.GeoJsonTooltip(fields=['us_dscr'], aliases=['Uso de Suelo:'])
).add_to(m)

# Añadir la leyenda
def generate_legend_html(color_dict):
    html = '''
    <div style="
        position: fixed;
        bottom: 50px;
        left: 50px;
        width: 300px;
        background-color: white;
        border:2px solid grey;
        z-index:9999;
        font-size:12px;
        padding: 10px;
        max-height: 300px;
        overflow-y: auto;
        ">
        <b>Usos de Suelo</b><br>
    '''
    for uso, color in color_dict.items():
        html += f'<i style="background:{color};width:12px;height:12px;float:left;margin-right:8px;"></i>{uso}<br>'
    html += '</div>'
    return html

legend_html = generate_legend_html(color_dict)
m.get_root().html.add_child(folium.Element(legend_html))

# Ajustar el mapa a los límites de los datos
bounds = gdf_manzanas_coyoacan.total_bounds  # [minx, miny, maxx, maxy]
m.fit_bounds([[bounds[1], bounds[0]], [bounds[3], bounds[2]]])

# Mostrar el mapa
m

In [4]:
manzanas_shp = '../data/manzanas/090030001m.shp'
gdf_manzanas = gpd.read_file(manzanas_shp)

In [5]:
gdf_manzanas =

,IDENTIFICA,CVEGEO,geometry
0,1,0900300011497015,"POLYGON ((2803618.272 816084.655, 2803629.084 ..."
1,2,0900300010713073,"POLYGON ((2800050.629 817743.071, 2800047.704 ..."
2,3,0900300010855034,"POLYGON ((2799116.786 816540.751, 2799115.55 8..."
3,4,0900300011251001,"POLYGON ((2802183.591 818100.751, 2802195.869 ..."
4,5,0900300011251026,"POLYGON ((2802247.866 818010.814, 2802247.655 ..."
...,...,...,...
4808,4809,0900300011548024,"POLYGON ((2796078.568 815297.134, 2796077.364 ..."
4809,4810,0900300011336014,"POLYGON ((2802896.383 816945.221, 2802906.594 ..."
4810,4811,0900300011660030,"POLYGON ((2797303.256 814730.717, 2797305.219 ..."
4811,4812,090030001150A023,"POLYGON ((2803218.608 815809.155, 2803207.165 ..."
4812,4813,0900300010658025,"POLYGON ((2798423.528 816648.787, 2798430.977 ..."

## Queremos ver como estan relaciondas las colonias y las manzanas con el CVEGEO

In [6]:
ageb_shp = '~/Downloads/poligono_ageb_urbanas_cdmx/poligono_ageb_urbanas_cdmx.shp'
gdf_ageb = gpd.read_file(ageb_shp)

In [7]:
print(gdf_ageb.head())

          CVEGEO CVE_ENT CVE_MUN CVE_LOC CVE_AGEB  \
0  0901000011716      09     010    0001     1716
1  0901000012150      09     010    0001     2150
2  0901000011133      09     010    0001     1133
3  0901000011307      09     010    0001     1307
4  0901000010281      09     010    0001     0281

                                            geometry
0  POLYGON ((-99.25882 19.32558, -99.25834 19.325...
1  POLYGON ((-99.1917 19.37893, -99.1917 19.37879...
2  POLYGON ((-99.1776 19.35182, -99.17766 19.3517...
3  POLYGON ((-99.20805 19.31277, -99.20768 19.312...
4  POLYGON ((-99.24228 19.38451, -99.24233 19.384...

In [9]:
print(gdf_ageb.columns)
print(gdf_ageb.crs)
print(gdf_ageb.geometry)

Index(['CVEGEO', 'CVE_ENT', 'CVE_MUN', 'CVE_LOC', 'CVE_AGEB', 'geometry'], dtype='object')
EPSG:4326
0       POLYGON ((-99.25882 19.32558, -99.25834 19.325...
1       POLYGON ((-99.1917 19.37893, -99.1917 19.37879...
2       POLYGON ((-99.1776 19.35182, -99.17766 19.3517...
3       POLYGON ((-99.20805 19.31277, -99.20768 19.312...
4       POLYGON ((-99.24228 19.38451, -99.24233 19.384...
                              ...
2426    POLYGON ((-99.00253 19.35744, -99.00255 19.355...
2427    POLYGON ((-98.99932 19.35467, -98.99889 19.354...
2428    POLYGON ((-98.98392 19.34561, -98.98367 19.345...
2429    POLYGON ((-99.06016 19.36342, -99.06042 19.362...
2430    POLYGON ((-99.0568 19.36313, -99.0576 19.35951...
Name: geometry, Length: 2431, dtype: geometry

In [11]:
# Verifica que ambos GeoDataFrames tengan el mismo CRS
gdf_manzanas = gdf_manzanas.to_crs(gdf_ageb.crs)

# Realiza un cruce espacial
gdf_manzanas_ageb = gpd.sjoin(gdf_manzanas, 
                              gdf_ageb, 
                              how="left", 
                              predicate="intersects")

# Visualiza los datos combinados
print(gdf_manzanas_ageb.head())

   IDENTIFICA       CVEGEO_left  \
0           1  0900300011497015
1           2  0900300010713073
2           3  0900300010855034
3           4  0900300011251001
4           5  0900300011251026

                                            geometry  index_right  \
0  POLYGON ((-99.10271 19.31447, -99.10261 19.314...         1946
1  POLYGON ((-99.13643 19.33014, -99.13646 19.330...         1845
2  POLYGON ((-99.14557 19.31942, -99.14559 19.319...         1879
3  POLYGON ((-99.11601 19.33299, -99.1159 19.3329...         1921
4  POLYGON ((-99.11542 19.33216, -99.11542 19.332...         1921

    CVEGEO_right CVE_ENT CVE_MUN CVE_LOC CVE_AGEB
0  0900300011497      09     003    0001     1497
1  0900300010713      09     003    0001     0713
2  0900300010855      09     003    0001     0855
3  0900300011251      09     003    0001     1251
4  0900300011251      09     003    0001     1251

In [12]:
import geopandas as gpd

# Lista de shapefiles con rutas completas
shapefiles = [
    "~/Downloads/09/DISTRITO.shp",
    "~/Downloads/09/ENTIDAD.shp",
    "~/Downloads/09/MUNICIPIO.shp",
    "~/Downloads/09/SECCION.shp"
]

# Explorar cada shapefile
for shp in shapefiles:
    print(f"Explorando {shp}...")
    try:
        gdf = gpd.read_file(shp)
        print("Columnas disponibles:", gdf.columns)
        print("Primeras filas:\n", gdf.head(), "\n")
        print("Sistema de referencia (CRS):", gdf.crs, "\n")
    except Exception as e:
        print(f"Error leyendo {shp}: {e}\n")

Explorando ~/Downloads/09/DISTRITO.shp...
Columnas disponibles: Index(['gid', 'id', 'entidad', 'distrito', 'tipo', 'control', 'geometry1_',
       'geometry'],
      dtype='object')
Primeras filas:
    gid   id  entidad  distrito  tipo  control geometry1_  \
0    1  1.0        9         1     6      0.0       None
1    2  2.0        9         2     7      0.0       None
2    3  3.0        9         3     6      0.0       None
3    4  4.0        9         4     6      0.0       None
4    5  5.0        9         5     7      0.0       None

                                            geometry
0  POLYGON ((486884.035 2166534.968, 487088.745 2...
1  POLYGON ((486955.834 2158280.658, 486971.543 2...
2  POLYGON ((478505.353 2157846.004, 478520.669 2...
3  POLYGON ((491075.959 2138646.711, 491305.972 2...
4  POLYGON ((485837.484 2134940.874, 486046.859 2...

Sistema de referencia (CRS): EPSG:32614

Explorando ~/Downloads/09/ENTIDAD.shp...
Columnas disponibles: Index(['gid', 'id', 'entidad', 'nombre', 'circunscri', 'crc', 'control',
       'geometry1_', 'geometry'],
      dtype='object')
Primeras filas:
    gid   id  entidad            nombre  circunscri  crc  control geometry1_  \
0    1  1.0        9  DISTRITO FEDERAL           4    6      1.0       None

                                            geometry
0  POLYGON ((489779.266 2157552.414, 489939.092 2...

Sistema de referencia (CRS): EPSG:32614

Explorando ~/Downloads/09/MUNICIPIO.shp...
Columnas disponibles: Index(['gid', 'id', 'entidad', 'municipio', 'nombre', 'control', 'geometry1_',
       'geometry'],
      dtype='object')
Primeras filas:
    gid    id  entidad  municipio                 nombre  control geometry1_  \
0    1  21.0        9         10         ALVARO OBREGON     25.0       None
1    2   1.0        9          2           AZCAPOTZALCO      1.0       None
2    3  10.0        9         14          BENITO JUAREZ     13.0       None
3    4  17.0        9          3               COYOACAN     21.0       None
4    5  18.0        9          4  CUAJIMALPA DE MORELOS     22.0       None

                                            geometry
0  POLYGON ((471795.501 2135361.978, 471788.431 2...
1  POLYGON ((478474.329 2157819.27, 478483.24 215...
2  POLYGON ((483997.002 2145544.592, 484208.327 2...
3  POLYGON ((479220.379 2137743.499, 479197.272 2...
4  POLYGON ((472139.963 2141018.604, 472151.508 2...

Sistema de referencia (CRS): EPSG:32614

Explorando ~/Downloads/09/SECCION.shp...
Columnas disponibles: Index(['gid', 'id', 'entidad', 'distrito', 'municipio', 'seccion', 'tipo',
       'control', 'geometry1_', 'geometry'],
      dtype='object')
Primeras filas:
    gid      id  entidad  distrito  municipio  seccion  tipo  control  \
0    1  1727.0        9         1          5      821     2   1749.0
1    2  1728.0        9         1          5      822     2   1750.0
2    3  1726.0        9         1          5      823     2   1748.0
3    4  1725.0        9         1          5      824     2   1747.0
4    5  1730.0        9         1          5      825     2   1752.0

  geometry1_                                           geometry
0       None  POLYGON ((486148.93 2165923.68, 486299.804 216...
1       None  POLYGON ((486270.995 2164283.639, 486281.266 2...
2       None  POLYGON ((485330.589 2165055.111, 485434.542 2...
3       None  POLYGON ((485293.899 2164682.1, 485307.148 216...
4       None  POLYGON ((486817.919 2163579.663, 486838.837 2...

Sistema de referencia (CRS): EPSG:32614